---
version: "2.2"

volumes:
  certs:
    external: true
  certs-data:
    external: true

services:
  #---------------------------------------------------------------------------#
  # Push API Gateway                                                        #
  #---------------------------------------------------------------------------#
  radar-push-endpoint:
    image: covidcollab/radar-push-endpoint:dev
    depends_on:
      - redis
      - schema-registry-1
    ports:
      - 8090:8090
    volumes:
      - ./etc/push-endpoint/gateway.yml:/etc/radar-gateway/gateway.yml
      - ${GOOGLE_CREDENTIALS_FILE_PATH}:/opt/google_credentials.json
      - "${KAFKA_SSL_TRUSTSTORE_LOCATION}:/kafka-truststore"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /opt/google_credentials.json

  redis:
    image: bitnami/redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
    restart: always
    volumes:
      - "${REDIS_DATA_PATH}:/bitnami/redis/data"

  #---------------------------------------------------------------------------#
  # Schema Registry                                                           #
  #---------------------------------------------------------------------------#
  schema-registry-1:
    image: confluentinc/cp-schema-registry:6.1.0
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - "${KAFKA_SSL_TRUSTSTORE_LOCATION}:/kafka-truststore"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: ${ZOOKEEPER}
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      SCHEMA_REGISTRY_HOST_NAME: schema-registry-1
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_AVRO_COMPATIBILITY_LEVEL: none
      SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_LOCATION: "/kafka-truststore"
      SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: SSL
      KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS: 5000


  #---------------------------------------------------------------------------#
  # Webserver                                                                 #
  #---------------------------------------------------------------------------#
  webserver:
    image: nginx:1.14.0-alpine
    restart: always
    depends_on:
      - radar-push-endpoint
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/letsencrypt
      - certs-data:/data/letsencrypt
      - "./etc/webserver/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./etc/webserver/cors.conf:/etc/nginx/cors.conf:ro"
      - "./etc/webserver/ip-access-control.conf:/etc/nginx/ip-access-control.conf:ro"
    # healthcheck hard to do, however, it is possible to monitor this externally
    # with
    # docker logs --since 2m radarcphadoopstack_webserver_1 | grep "connect() failed"
